name: Deploy on VPS
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/dev/quentin-aslan-strapi
            git pull origin main
            npm ci
            NODE_ENV=production npm run build
            sudo systemctl restart quentin-aslan-strapi